### ISSUE TITLE
NetworkX-only benchmarks (no backends)

### ISSUE THREAD

**Issue by dschult** [dPys/nxbench#29]
There are many parameters that we vary across tests, including comparison to backends.
But it might be very useful to have comparisons just within NetworkX.

Could we bake in NetworkX as if it is one of the backends to allow the parameter sweep to have only one value (such as NetworkX) in the backends dimension?

**Comment by dPys** [comment]
Yes indeed! So this is absolutely possible just by specifying networkx alone in the `backends` section of `environ` in the config yaml, e.g.:
```
algorithms:
  - name: "pagerank"
    func: "networkx.pagerank"
    params:
      alpha: 0.9
      tol: 1.0e-6
    requires_directed: false
    groups: ["centrality", "random_walk"]

  - name: "eigenvector_centrality"
    func: "networkx.eigenvector_centrality"
    params:
      max_iter: 500
      tol: 1e-06
    requires_directed: false
    groups: ["centrality", "path_based"]
    validate_result: "nxbench.validation.validate_node_scores"

datasets:
  - name: "erdos_renyi_small"
    source: "generator"
    params:
      generator: "networkx.erdos_renyi_graph"
      n: 1000
      p: 0.01
    metadata:
      directed: false
      weighted: false

  - name: "barabasi_albert_small"
    source: "generator"
    params:
      generator: "networkx.barabasi_albert_graph"
      n: 1000
      m: 3
    metadata:
      directed: false
      weighted: false
      
  - name: "powerlaw_cluster"
    source: "generator"
    params:
      generator: "networkx.powerlaw_cluster_graph"
      n: 1000
      m: 2
      p: 0.1
    metadata:
      directed: false
      weighted: false

validation:
  skip_slow: false
  validate_all: true
  error_on_fail: true
  report_memory: true

environ:
  backend:
    networkx:
      - "networkx==3.4.1"
  num_threads:
    - "1"
    - "4"
    - "8"
  pythons:
    - "3.10"
```

This works because by default, `networkx` (with no dispatching to third-party libraries) is treated as a [registered backend](https://github.com/dPys/nxbench/blob/main/nxbench/backends/registry.py#L14-L28).
